### ISSUE TITLE
運勢占い機能を追加する

### ISSUE THREAD

**Issue by takanori-matsumoto-mulodo** [vumui/study#1]
以下の要件に従って、新しい機能を追加して下さい

### 今の仕様
* "診断"ボタンをクリックしたときに、診断した人の"タイプ"が表示されます。

### 新しい仕様
* "診断"ボタンをクリックしたときに、診断した人の"タイプ"と、"運勢"を表示する。
* "運勢"として、"大吉", "中吉", "小吉", "末吉", "凶", "大凶"の6種類のいずれかを表示する。
* 画面上の表示形式は、"〜さんの今日の運勢は"大凶"です!"、のような表示とする。
* "タイプ"の表示はそのまま残して下さい。

**Comment by takanori-matsumoto-mulodo** [comment]
@vumui
"ツイートする"を押したときのメッセージにも"運勢"を追加しましょう。

作業が終わったら、"@takanori-matsumoto-mulodo"のメンションを付けて、このページにCommentをお願いします！（そうすることで、メールの通知が飛びます）

**Comment by vumui** [comment]
"ツイートする"を押したときのメッセージにも"運勢"を追加しました。確認お願いします。

**Comment by vumui** [comment]
＠takanori-matsumoto
"ツイートする"を押したときのメッセージにも"運勢"を追加しました。確認お願いします。

**Comment by takanori-matsumoto-mulodo** [comment]
@vumui 
LGTM!
